### PR TITLE
Add Haskell icons

### PR DESCRIPTION
**Pull request by cmd-johnson**
Add icons for Haskell (`.hs`) and Literate Haskell (`.lsh`) files, as well as the flask icon for Haskell Specs.

Works fine with Atom Dark and Atom Material themes, but using the One Dark theme the Haskell icons are offset a bit to the bottom:
Icons appear offset using One Dark

Not sure how to fix that, I tried what was done with the `.go` and `.java` icons and explicitly set `top: 0px !important;` what fixed the issue on One Dark but moved the icons too high on Atom Dark and Atom Material.

### CODE REVIEW

**Comment by swrobel** [comment]
Haskell icons look a little bit too small to discern ... maybe bump up the font-size a bit? See https://github.com/lee-dohm/file-type-icons/blob/master/styles/icons.less#L32

**Comment by cmd-johnson** [comment]
Agreed, one question though:
Applying a larger font size to the haskell-icon class will increase the font size for all files in the tree ending with `.hs`, even the test files, which obviously shouldn't be scaled since they use a completely different icon.
Is there any way to tell Atom to only apply the .haskell-icon class to `*.hs` files but not `*Spec.hs` files?
Alternatively I could apply a font-size to the test-file-icon class, too, but I'd rather not do that if there's any way around it.

**Comment by cmd-johnson** [comment]
Nevermind, figured it out.
I set the icon's font-size to 155%, which makes it approximately as wide as the other icons.
The icon still appears too low on One Dark

**Comment by lee-dohm** [comment]
Thanks for this!

**Pull request merged**
